### ISSUE TITLE
Ридми как у индусов

### ISSUE THREAD

**Issue by Haze272** [dronikosha/dronikosha#1]
Ура! Теперь с этими смайликами твой профиль похож на senior full-all-stack indian developer

**Comment by neluckoff** [comment]
Да не говори, так еще и в километр вниз

**Comment by dronikosha** [comment]
Что тебе не нравится, классный ридми, ты просто завидуешь.

**Comment by dronikosha** [comment]
Лучше б звезду поставил

**Comment by Haze272** [comment]
Вон у Димы смотри какие красивые плтитки, а автор твоего репозитория индус. Вопрос решён.

**Comment by dronikosha** [comment]
У димы казахские плитки
И вообще, чем тебе индусы не угодили, это лучшие разработчики
Ты без них бы даже компьютер не научился включать
